JMS/Controllers/Masters/JewelTypeMasterController.cs
using JMS.BAL.BussinesLogic;
using JMS.BAL.ViewModel;
using JMS.Models;
using log4net;
using System;
using System.Linq;
using System.Web.Mvc;

namespace JMS.Controllers
{
    public class JewelTypeMasterController : Controller
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(JewelTypeMasterController));
        public ActionResult Index()
        {
            try
            {
                var jeweTypeModel = new JewelTypeViewModel
                {
                    StatusList = HelperBAL.StatusList
                };
                return View(jeweTypeModel);
            }
            catch (Exception ex)
            {
                Log.Error("JewelTypeMasterController-Index-Exception", ex);
                return null;
            }
        }
        public ActionResult GetJewelTypeJsonData(JqueryDatatableParam param)
        {
            try
            {
                var jewelTypeObj = new JewelTypeBAL();
                var jewelTypes = jewelTypeObj.GetAllJewelTypes().Items;
                if (!string.IsNullOrEmpty(param.sSearch))
                {
                    jewelTypes = jewelTypes.Where(x => x.Id.ToString().ToLower() != null && x.Id.ToString().ToLower().Contains(param.sSearch.ToLower())
                               || x.JewelTypeName != null && x.JewelTypeName.ToLower().Contains(param.sSearch.ToLower())).ToList();

                }

                var sortColumnIndex = Convert.ToInt32(HttpContext.Request.QueryString["iSortCol_0"]);
                var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
                switch (sortColumnIndex)
                {
                    case 0:
                        jewelTypes = sortDirection == "asc" ? jewelTypes.OrderBy(c => c.Id).ToList() : jewelTypes.OrderByDescending(c => c.Id).ToList();
                        break;
                    case 1:
                        jewelTypes = sortDirection == "asc" ? jewelTypes.OrderBy(c => c.JewelTypeName).ToList() : jewelTypes.OrderByDescending(c => c.JewelTypeName).ToList();
                        break;
                    case 2:
                        jewelTypes = sortDirection == "asc" ? jewelTypes.OrderBy(c => c.StatusName).ToList() : jewelTypes.OrderByDescending(c => c.StatusName).ToList();
                        break;
                }

                var displayResult = jewelTypes.Skip(param.iDisplayStart)
                                         .Take(param.iDisplayLength == -1 ? jewelTypes.Count : param.iDisplayLength).ToList();

                var totalRecords = jewelTypes.Count;

                return Json(new
                {
                    param.sEcho,
                    iTotalRecords = totalRecords,
                    iTotalDisplayRecords = totalRecords,
                    aaData = displayResult
                }, JsonRequestBehavior.AllowGet);
            }
            
            catch (Exception ex)
            {
                Log.Error("JewelTypeMasterController-GetJewelTypeJsonData-Exception", ex);
                return Json(new { data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult CreateOrUpdate(JewelTypeModel model)
         {
            try
            {
                var jewelTypeBALObj = new JewelTypeBAL();
                if (jewelTypeBALObj.GetJewelTypeById(model.Id) != null)
                {
                    jewelTypeBALObj.UpdateJewelType(model);
                    return Json(new { data = "Updated" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    jewelTypeBALObj.AddJewelType(model);
                    return Json(new { data = "Added" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                Log.Error("JewelTypeMasterController-CreateOrUpdate-Exception", ex);
                throw;
            }
        }
        [HttpPost]
        public ActionResult DeleteJewelType(int Id)
        {
            try
            {
                var jewelTypeBALObj = new JewelTypeBAL();
                jewelTypeBALObj.DeleteJewelType(Id);

                return Json(new { data = "deleted" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error("JewelTypeMasterController-DeleteJewelType-Exception", ex);
                return Json(new { data = ex.Message }, JsonRequestBehavior.AllowGet);

            }
        }
    }
}

JMS/Views/JewelTypeMaster/Index.cshtml
@using JMS.BAL.ViewModel
@model JMS.BAL.ViewModel.JewelTypeViewModel

@{
    ViewBag.Title = "Jewel Type List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = Session["LoggedInUser"] as LoggedInUserModel;
    if (user?.Role != 1)
    {
        Response.Redirect("~/Login/Index");
    }
}


<div class="card card-outline card-primary">
    <div class="card-header">
        <div class="float-left">
            <h3>@ViewBag.Title</h3>
        </div>
        <div class="float-right">
            <button class="btn btn-primary" onclick="createJewelTypeFunction()" data-toggle="modal" data-target="#jewelTypeModalPopup">
                <i class="fas fa-plus "></i>
                Add New Jewel Type
            </button>
        </div>
    </div>
    <div class="card-body">
        <table id="jewelTypeTable" class="table table-bordered table-striped ">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                       Name
                    </th>

                    <th>
                        Status
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
        </table>
    </div>

    @using (Html.BeginForm("CreateOrUpdate", "JewelTypeMaster",FormMethod.Post, new { id = "jewelTypeform" }))
    {
        <div id="jewelTypeModalPopup" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Jewel Type Details Form</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @Html.HiddenFor(m => m.Id )
                        <div class="form-group">
                            <div class="row">
                                <label class="col-3"> Jewel Type<span style="color:red">*</span></label>
                                <div class="col-9 validation-msg">
                                    @Html.TextBoxFor(m => m.JewelTypeName, new { @class = "form-control " })
                                </div>
                        
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">

                                <label class="col-3">Status</label>
                                <div class="col-9">
                                    @Html.DropDownListFor(m => m.Status, Model.StatusList, new { @class = "form-control " })
                                </div>
                               
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("DeleteJewelType", "JewelTypeMaster", FormMethod.Post, new { id = "jewelTypeDeleteform" }))
    {
        <div id="jewelTypeDeleteModalPopup" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Delete Jewel Type</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @Html.HiddenFor(m => m.Id, new { id = "deletejewelTypeId" })
                        <p> Are you sure want to delete "<label id="deleteJewelTypeName"></label>" Jewel Type?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Jewel Type</button>
                    </div>
                </div>
            </div>
        </div>
    }
    @Scripts.Render("~/Content/jewelType")
</div>