JMS/Controllers/Masters/CompanyMasterController.cs
using JMS.BAL.BussinesLogic;
using JMS.BAL.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using PagedList;
using JMS.Models;
using System.Linq;
using log4net;

namespace JMS.Controllers
{
    public class CompanyMasterController : Controller
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(CompanyMasterController));
      
        public ActionResult Index()
        {
            try
            {
                var companyViewModel = new CompanyViewModel
                {
                    StatusList = HelperBAL.StatusList
                };
                return View(companyViewModel);
            }
            catch (Exception ex)
            {
                Log.Error("CompanyMasterController-Index-Exception", ex);
                return null;//To-do: Redirect to Error Page 
            }
        }
        public ActionResult GetCompanyJsonData(JqueryDatatableParam param)
        {
            try
            {
                var companyBalObj = new CompanyBAL();
                var companies = companyBalObj.GetAllCompany().Items;

                if (!string.IsNullOrEmpty(param.sSearch))
                {

                    companies = companies.Where(x => x.Id.ToString().ToLower() != null && x.CompanyName.ToLower().Contains(param.sSearch.ToLower())
                                                  || x.Id.ToString().ToLower()!=null&&x.Id.ToString().ToLower().Contains( param.sSearch.ToLower())).ToList();
                }

                var sortColumnIndex = Convert.ToInt32(HttpContext.Request.QueryString["iSortCol_0"]);
                var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
                switch (sortColumnIndex)
                {
                    case 0:
                        companies = sortDirection == "asc" ? companies.OrderBy(c => c.Id).ToList() : companies.OrderByDescending(c => c.Id).ToList();
                        break;
                    case 1:
                        companies = sortDirection == "asc" ? companies.OrderBy(c => c.CompanyName).ToList() : companies.OrderByDescending(c => c.CompanyName).ToList();
                        break;
                    case 2:
                        companies = sortDirection == "asc" ? companies.OrderBy(c => c.StatusName).ToList() : companies.OrderByDescending(c => c.StatusName).ToList();
                        break;
                }

                var displayResult = companies.Skip(param.iDisplayStart)
                                         .Take(param.iDisplayLength == -1 ? companies.Count : param.iDisplayLength).ToList();

                var totalRecords = companies.Count;

                return Json(new
                {
                    param.sEcho,
                    iTotalRecords = totalRecords,
                    iTotalDisplayRecords = totalRecords,
                    aaData = displayResult
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error("CompanyMasterController-GetCompanyJsonData-Exception", ex);
                return Json(new { data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult CreateOrUpdate(CompanyModel model)
        {
            try
            {
                var companyBalObj = new CompanyBAL();
                if (companyBalObj.GetCompanyById(model.Id) != null)
                {
                    companyBalObj.UpdateCompany(model);
                    return Json(new { data = "Updated" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    companyBalObj.AddCompany(model);
                    return Json(new { data = "Created" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                Log.Error("CompanyMasterController-CreateOrUpdate-Exception", ex);
                return Json(new { data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult DeleteCompany(int Id)
        {
            try
            {
                var companyBalObj = new CompanyBAL();
                companyBalObj.DeleteCompany(Id);
                return Json(new { data = "deleted" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error("CompanyMasterController-DeleteCompany-Exception", ex);
                return Json(new { data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

JMS/Views/CompanyMaster/Index.cshtml
@using JMS.BAL.ViewModel
@model JMS.BAL.ViewModel.CompanyViewModel

@{
    ViewBag.Title = "Company List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = Session["LoggedInUser"] as LoggedInUserModel;
    if (user?.Role != 1)
    {
        Response.Redirect("~/Login/Index");
    }
}


<div class="card card-outline card-primary">
    <div class="card-header">
        <div class="float-left">
            <h3>@ViewBag.Title</h3>
        </div>
        <div class="float-right">
            <button class="btn btn-primary" onclick="createCompanyFunction()" data-toggle="modal" data-target="#companyModalPopup">
                <i class="fas fa-plus "></i>
                Add New Company
            </button>
        </div>
    </div>
    <div class="card-body">
        <table id="CompanyTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Name
                    </th>

                    <th>
                        Status
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
          
        </table>
    </div>

    @using (Html.BeginForm("CreateOrUpdate", "CompanyMaster", FormMethod.Post, new { id = "Companyform" }))
    {
        <div id="companyModalPopup" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Company Details Form</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @Html.HiddenFor(m => m.Id)
                        <div class="form-group">
                            <div class="row">
                                <label class="col-3"> Name<span style="color:red">*</span></label>
                                <div class="col-9 validation-msg">
                                    @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control " })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-3">Status</label>
                                <div class="col-9">
                                    @Html.DropDownListFor(m => m.Status, Model.StatusList, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("DeleteCompany", "CompanyMaster", FormMethod.Post, new { id = "companyDeleteform" }))
    {
        <div id="companyDeleteModalPopup" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Delete Company</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @Html.HiddenFor(m => m.Id)
                        <p> Are you sure want to delete "<label id="deleteCompanyName"></label>" Company?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Company</button>
                    </div>
                </div>
            </div>
        </div>
    }
    @Scripts.Render("~/Content/company")
</div>